### PR TITLE
Autofocus on password field

### PR DESCRIPTION
**Pull request by maksimf**
Save ourselves one click / tab press

### CODE REVIEW

**Comment by gblakeman** [comment]
@maksimf Thanks for the contribution!

Any opinion on this @danrabinowitz? In the past I didn’t like it because of how iOS “zoomed” the page in on auto-focused fields, but I don’t think that behavior exists anymore, so I’m more open to implementing it.

**Comment by danrabinowitz** [comment]
I like the idea. 👍

**Comment by danrabinowitz** [comment]
I'm traveling this week, and have poor network access, so I can test it myself until this weekend.

**Comment by gblakeman** [comment]
Thanks gents! I just pushed `1.4.5` with this update.

**Pull request merged**
