### PR TITLE
Allow Rails 5

### LINKED ISSUE #27: Rails 5 support
Could you please make this gem compatible with rails 5? When I try to install it I get:

``
conflicting dependencies rails (< 5, >= 3) and rails (~> 5.0.0, ~> 5.0.0) (Gem::DependencyResolutionError)
  Activated rails-5.0.0
  which does not match conflicting dependency (< 5, >= 3)
``

### PR DESCRIPTION
**Pull request by danrabinowitz**
This PR includes commits from https://github.com/gblakeman/lockup/pull/29

It allows using lockup with Rails 5.

Resolves #27.

### CODE REVIEW

**Comment by arael** [comment]
Thank you very much. How long before we are able to install this through the gem system?

**Comment by gblakeman** [comment]
@danrabinowitz Thanks for your work on this.

Did you check backwards compatibility with any of those? Or only Rails 5 compatibility?

@arael I'm traveling right now, but will get this merged and get a new version of the Gem pushed as soon as I can.

**Comment by danrabinowitz** [comment]
@gblakeman I didn't check every minor Rails version. We'd need a CI matrix to do that. But I tried it on a Rails 4 app, and it worked as expected.

Also, the vast majority of these changes are only needed for development and testing. The actual changes to the non-test code are pretty minimal.

Worst case... if any bugs are reported, we can write specs and fix them as they arise.

But I feel pretty good about this PR.

**Comment by danrabinowitz** [comment]
@arael If you want to use this before an official gem is released, you can use something like this
gem 'lockup', git: https://github.com/danrabinowitz/lockup.git, branch: 'allow_rails5'

**Comment by gblakeman** [comment]
@danrabinowitz Thanks Dan, really appreciate it. I’m merging it now. @arael, I’ll try to get this released sometime tomorrow, but in the meantime, you can follow Dan’s instructions.

**Comment by arael** [comment]
Thank you both.

**Pull request merged**
